### ISSUE TITLE
Help needed: some errors message, problems with the filter and spaghetti code

### ISSUE THREAD

**Issue by lucasvazq** [reviewdog/action-shellcheck#13]
Hi, I am having a couple of issues with using this action and I would like to receive help.

**1)** The first thing is that a warning message is being displayed when I use it. I would like to know if this is completely normal or is it a bug?

![2020-07-15-183658_956x234_scrot](https://user-images.githubusercontent.com/38964964/87600213-38fcb380-c6ca-11ea-80f5-9d7c675da949.png)

**2)** The second thing is, I'd like to know how I can run shellcheck over my entire file, rather than just the diff.
I have tried using the `filter_mode: nofilter` and `filter_mode: file` parameters but they were not successful (it may be due to the previous error)

_The same message for both was:_
![2020-07-15-183708_636x39_scrot](https://user-images.githubusercontent.com/38964964/87600254-3d28d100-c6ca-11ea-9a4e-42c6ddd968e1.png)

**3)** And finally, I have spaghetti code in my action because I want to run shellcheck against a lot of different files that don't have any similitude in the name, is there any solution for it?

**Here is my action:**
```yml
name: Linter [develop]

on:
  pull_request:
    branches:
      - develop

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Super-Linter
        uses: github/super-linter@v2.1.0
        env:
          VALIDATE_ALL_CODEBASE: false

      # Spaghetti code

      - name: shellcheck for ~/.zshrc
        uses: reviewdog/action-shellcheck@v1.0.0
        with:
          pattern: ".zshrc"
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
          filter_mode: file
          shellcheck_flags: '-s sh -e 1090,2004,2039'

      - name: shellcheck for ~/.local/bin/change-background
        uses: reviewdog/action-shellcheck@v1.0.0
        with:
          pattern: "change-background"
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
          filter_mode: file
          shellcheck_flags: '-s sh -e 1090,2004,2039'

      - name: shellcheck for ~/.local/bin/start-script
        uses: reviewdog/action-shellcheck@v1.0.0
        with:
          pattern: "start-script"
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
          filter_mode: file
          shellcheck_flags: '-s sh -e 1090,2004,2039'
```

Thanks for your time ⭐

**Comment by Vlaaaaaaad** [comment]
@lucasvazq it's likely a version mismatch.

You are using the `v1.0.0` version of `reviewdog/action-shellcheck`. That's pretty old. Could you use the latest version( `v1.3.0`) and report back?

The `shellcheck_flags` parameter that you are using was added in `v1.2.1` for example: https://github.com/reviewdog/action-shellcheck/releases/tag/v1.2.1

**Comment by shogo82148** [comment]
We recommend you to use `@v1` tag, because of https://github.com/reviewdog/action-template/issues/11

GitHub Marketplace says that the latest version is v1.0.0.
![image](https://user-images.githubusercontent.com/1157344/87606419-e5c04a80-c735-11ea-8a56-2e8b6826bb09.png)

but, actually, the latest version of action-shellcheck is [v1.3.0](https://github.com/reviewdog/action-shellcheck/releases/tag/v1.3.0).

**Comment by lucasvazq** [comment]
Thanks to both @Vlaaaaaaad @shogo82148 
I have updated the version and now its works for me

Here is how my action looks
```yml
name: Linter [develop]

on:
  pull_request:
    branches:
      - develop

jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Super-Linter
        uses: github/super-linter@v2.1.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH: false

      - name: shellcheck for ~/.zshrc
        uses: reviewdog/action-shellcheck@v1.3.0
        with:
          pattern: ".zshrc"
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
          filter_mode: nofilter
          shellcheck_flags: "-s sh -e 1090,1091,2004,2039"

      - name: shellcheck for ~/.local/bin/change-background
        uses: reviewdog/action-shellcheck@v1.3.0
        with:
          pattern: "change-background"
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
          filter_mode: nofilter
          shellcheck_flags: "-s sh -e 1090,1091,2004,2039"

      - name: shellcheck for ~/.local/bin/start-script
        uses: reviewdog/action-shellcheck@v1.3.0
        with:
          pattern: "start-script"
          github_token: ${{ secrets.REVIEWDOG_GITHUB_API_TOKEN }}
          filter_mode: nofilter
          shellcheck_flags: "-s sh -e 1090,1091,2004,2039"
```

I'm going to close the issue
