### ISSUE TITLE
fatal: ls-files -i must be used with either -o or -c

### ISSUE THREAD

**Issue by electronjoe** [reviewdog/action-shellcheck#21]
I'm actively exploring what's going on here - in [Magma's](https://github.com/magma/magma/blob/master/.github/workflows/hadolint.yml) GH Action execution of hadolint. This has started failing very recently with the below.

Error message.

```
 Running hadolint with reviewdog 🐶 ...
  reviewdog: This is Pull-Request from forked repository.
  GitHub token doesn't have write permission of Review API, so reviewdog will
  report results via logging command [1] and create annotations similar to
  github-pr-check reporter as a fallback.
  fatal: ls-files -i must be used with either -o or -c
  [1]: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/development-tools-for-github-actions#logging-commands
  parse error: Invalid numeric literal at line 1, column 7
  reviewdog: parse error: failed to unmarshal rdjson (DiagnosticResult): proto: syntax error (line 1:1): unexpected token 
Error: Process completed with exit code 1.
```

Our [GH Action](https://github.com/magma/magma/blob/master/.github/workflows/hadolint.yml).

```
name: reviewdog
on: [pull_request]
jobs:
  shellcheck:
    name: runner / shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.github_token }}
          filter_mode: added # Any added or changed content.
          reporter: github-pr-review # Post code review comments. Falls back to Annotations.
          pattern: "*.sh" # Optional.
          # Other options omitted here but possible.
          # - fail_on_error
          # - path
          # - exclude
          # - shellcheck_flags
```
