### ISSUE TITLE
Level seems to have no effect

### ISSUE THREAD

**Issue by asbjornu** [reviewdog/action-shellcheck#9]
I've configured `level: style` and while that produces quite a few errors locally, `reviewdog/action-shellcheck` [does not fail the build](https://github.com/SwedbankPay/git-directory-deploy/pull/1/checks?check_run_id=685370494#step:4:1). None of the errors I see locally are printed anywhere by `reviewdog/action-shellcheck`. Have I configured it wrong, somehow?

```yaml
- name: Shellcheck
  uses: reviewdog/action-shellcheck@v1
  with:
    github_token: ${{ secrets.GITHUB_TOKEN }}
    reporter: github-pr-review
    level: style
```

**Comment by haya14busa** [comment]
level is the same as reviewdog's `-level` flag and style is not valid option. https://github.com/reviewdog/action-shellcheck#level

**Comment by haya14busa** [comment]
You can use `shellcheck_flags` instead.

**Comment by asbjornu** [comment]
I see. Thanks. I tried setting `level` to `info` and adding `shellcheck_flags: --severity=style` but it still doesn't detect any faults in my `.sh` scripts.

```yaml
- name: Shellcheck
    uses: reviewdog/action-shellcheck@v1
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      reporter: github-pr-review
      level: info
      shellcheck_flags: --severity=style
```

I'm also a bit unsure how `shellcheck_flags` works. It says that its default value is `--external-sources`, so if I set `shellcheck_flags` to something else, does that mean `--external-sources` is unset? If that's the case, the check should fail for doing `source` on external sources as well, which it doesn't.
